name = "RemoteLogging"
uuid = "5da01632-ec10-4c9a-b79c-b5b34d2fc1d9"
authors = ["Rhahi <git@rhahi.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
